kind = "web"
previewPath = "/"
title = "OM SAI ENTERPRISES"
version = "1.0.0"
id = "artifacts/om-sai-enterprises"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20952

[services.development]
run = "pnpm --filter @workspace/om-sai-enterprises run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/om-sai-enterprises", "run", "build" ]
publicDir = "artifacts/om-sai-enterprises/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20952"
BASE_PATH = "/"
